site_name: 'ETHOS Labs - Tempest Documentation'
copyright: © 2024, ETHOS Labs, LLC  - Please Do Not Redistribute
site_author: Tim Fowler

theme:
  name: readthedocs

nav:
  - Home: index.md
  - 'Build Guide':
    - TEMPEST Components Guide: tempest_components.md
    - Building Your CubeSat: tempest_build_guide.md
  - Setup:
    - Connecting to Your Wifi: connecting_to_wifi.md

extra_css:
  - overrides/custom.css
